### PR TITLE
Add Contributors Table in README.md

### PR DESCRIPTION
**Pull request by samir-0711**
Updated Contributors Table in README.md
Issue #28 

In README.md
image

In CONTRIBUTORS.md
image

### CODE REVIEW

**Review by ksdkamesh99 — CHANGES_REQUESTED** [review]
There is a error in the link associated with contributors.md . Please do change it @samir-0711

**Comment by samir-0711** [comment]
@ksdkamesh99 All requested changes done

**Review by ksdkamesh99 — APPROVED** [review]
Looks fine @samir-0711 Will merge it soon

**Comment by samir-0711** [comment]
@ksdkamesh99 Kindly add DWOC and level label. Thanks

**Pull request merged**
